# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
#added a comment to make revision
trigger:

- main

 

pool:

  vmImage: ubuntu-latest

 

stages:

 

- stage: Build

  jobs:

  - deployment: deploy

    displayName: Deployment

    environment: Stage4

    strategy:

      runOnce:

        deploy:

          steps:

            - script: echo Deployment

              displayName: "Para Job 1"

 

- stage: parallel2

  dependsOn: Build

  jobs:

  - deployment: deploy

    displayName: Parallel deploy 2

    environment: Stage3

    strategy:

      runOnce:

        deploy:

          steps:

            - script: echo parallel job 2

              displayName: "Para Job 2"

 

- stage: Deploy

  jobs:

  - job: Exit

    steps:

    - script: echo "exiting"